#! /usr/bin/env bash

# Copyright 2013 Chen Ruichao <linuxer.sheep.0x@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Notes
#   If you write '   3   Foo   bar    ', the weight will be 3 and the name 'Foo   bar'

declare -i total_weight=0
declare -a map
declare -A used

function init() {
    local weight name
    while read weight name; do
        for (( ; weight > 0; weight-- ))
          do map[total_weight++]=$name; done
        used[$name]=false
    done
}

init << EOF
6 食堂
6 西北拉面
2 悟饕
2 信华肉包
2 M.O.S
2 全家福
2 御面堂
1 MacDonald's
1 天天多多乐
EOF

declare -i used_cnt=0
for i in $( shuf -i 0-$((total_weight - 1)) ); do
    name=${map[i]}
    if [[ ${used[$name]} == true ]]
      then continue
      else used[$name]=true
    fi
    if (( used_cnt == 0 ))
      then echo -e "\e[1m$name\e[0m"
      else echo "$name"
    fi
    used_cnt=used_cnt+1
done
